# This workflow will do a new deploy of the vue app to gh pages

name: Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install vue-cli
      run: npm install @vue/cli
      
    - name: Build for production
      run: npm run build
      
    - name: Commit changes 
      run: |
        cd dist
        git config --global user.name ${{ secrets.USER_NAME }}
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git init
        git add -A
        git commit -m 'new Deployment'
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: dist

